### ISSUE TITLE
Prep for 2k19

### ISSUE THREAD

**Issue by FWirtz** [HackHPI/hackhpi.github.io#103]
## ToDos
- [ ] get all text changes from @danthe96 @annkatrinkuessner etc.
- [ ] add privacy notice on website
- [ ] change contact/imprint details
- [ ] migrate 2018 version to `/2018`
- [ ] change primary color
- [ ] add text changes to html site
- [ ] ...

**Comment by FWirtz** [comment]
CC @danthe96 @annkatrinkuessner @jak-ing ❤️

**Comment by tommartensen** [comment]
* [ ] change title
* [ ] change logos for download
* [] change team

**Comment by tommartensen** [comment]
I guess this is done @FWirtz 🤣
